/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseChatGroupMetadataParticipants;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Метаданные группы, если чат является группой
 */
@Schema(description = "Метаданные группы, если чат является группой")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-09-07T09:16:17.666Z[GMT]")
public class ResponseChatGroupMetadata {
  @SerializedName("id")
  private String id = null;

  @SerializedName("creation")
  private Integer creation = null;

  @SerializedName("owner")
  private String owner = null;

  @SerializedName("size")
  private Integer size = null;

  @SerializedName("participants")
  private List<ResponseChatGroupMetadataParticipants> participants = null;

  public ResponseChatGroupMetadata id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Идентификатор группы в формате WhatsApp
   * @return id
  **/
  @Schema(description = "Идентификатор группы в формате WhatsApp")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResponseChatGroupMetadata creation(Integer creation) {
    this.creation = creation;
    return this;
  }

   /**
   * Дата создания группы в формате Unix Time Stamp
   * @return creation
  **/
  @Schema(description = "Дата создания группы в формате Unix Time Stamp")
  public Integer getCreation() {
    return creation;
  }

  public void setCreation(Integer creation) {
    this.creation = creation;
  }

  public ResponseChatGroupMetadata owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Идентификатор создателя группы в формате WhatsApp
   * @return owner
  **/
  @Schema(description = "Идентификатор создателя группы в формате WhatsApp")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public ResponseChatGroupMetadata size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Количество участников в группе
   * @return size
  **/
  @Schema(description = "Количество участников в группе")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public ResponseChatGroupMetadata participants(List<ResponseChatGroupMetadataParticipants> participants) {
    this.participants = participants;
    return this;
  }

  public ResponseChatGroupMetadata addParticipantsItem(ResponseChatGroupMetadataParticipants participantsItem) {
    if (this.participants == null) {
      this.participants = new ArrayList<ResponseChatGroupMetadataParticipants>();
    }
    this.participants.add(participantsItem);
    return this;
  }

   /**
   * Массив участников
   * @return participants
  **/
  @Schema(description = "Массив участников")
  public List<ResponseChatGroupMetadataParticipants> getParticipants() {
    return participants;
  }

  public void setParticipants(List<ResponseChatGroupMetadataParticipants> participants) {
    this.participants = participants;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseChatGroupMetadata responseChatGroupMetadata = (ResponseChatGroupMetadata) o;
    return Objects.equals(this.id, responseChatGroupMetadata.id) &&
        Objects.equals(this.creation, responseChatGroupMetadata.creation) &&
        Objects.equals(this.owner, responseChatGroupMetadata.owner) &&
        Objects.equals(this.size, responseChatGroupMetadata.size) &&
        Objects.equals(this.participants, responseChatGroupMetadata.participants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creation, owner, size, participants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseChatGroupMetadata {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creation: ").append(toIndentedString(creation)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
