/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Error;
import io.swagger.client.model.GetmediaBody;
import io.swagger.client.model.InlineResponse2003;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for _Api
 */
@Ignore
public class _ApiTest {

    private final _Api api = new _Api();

    /**
     * Возвращает объект медиафайла, прикрепленного к сообщению
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMediaPostTest() throws Exception {
        GetmediaBody body = null;
        InlineResponse2003 response = api.getMediaPost(body);

        // TODO: test validations
    }
}
