/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CheckBody;
import io.swagger.client.model.Error;
import io.swagger.client.model.GetchatsBody;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse2004;
import io.swagger.client.model.SeenBody;
import io.swagger.client.model.SendBody;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Проверка зарегистрирован ли номер в WhatsApp
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void checkPostTest() throws Exception {
        CheckBody body = null;
        InlineResponse2001 response = api.checkPost(body);

        // TODO: test validations
    }
    /**
     * Возвращает список активных чатов
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getChatsPostTest() throws Exception {
        GetchatsBody body = null;
        InlineResponse2002 response = api.getChatsPost(body);

        // TODO: test validations
    }
    /**
     * Отправляет команду в чат, что последние сообщения просмотрены
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void seenPostTest() throws Exception {
        SeenBody body = null;
        InlineResponse2004 response = api.seenPost(body);

        // TODO: test validations
    }
    /**
     * Отправка сообщения
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sendMessageTest() throws Exception {
        SendBody body = null;
        InlineResponse200 response = api.sendMessage(body);

        // TODO: test validations
    }
}
